const express = require('express');
const cors = require('cors');
const { notFound, errorHandler } = require('./middleware/errorHandler');
const app = express();
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173' }));
app.use(express.json({ limit: '100kb' }));
app.get('/api/health', (_q, res) => res.json({ success: true, data: { status: 'ok' } }));
app.use('/api', require('./routes/habitRoutes'), require('./routes/analyticsRoutes'), require('./routes/settingsRoutes'));
app.use(notFound); app.use(errorHandler);
module.exports = app;
